### ISSUE TITLE
Wrong include for uaccess.h

### ISSUE THREAD

**Issue by jo-ruch** [troglobit/pibang#2]
The new Raspbian uses <linux/uaccess.h> instead of <asm/uaccess.h>.

**Comment by troglobit** [comment]
Good catch, would it work on older Raspbian releases to change to <linux/uaccess.h>, or would we need to check at build time?

**Comment by jo-ruch** [comment]
I can't confirm at the moment. I cant compile on raspberry pi 1b with raspbian wheezy but for different reasons. I'm fairly shure this will work on raspi 2b and above (> armv6).
